# .render.yaml

services:
  - name: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    env:
      - name: DATABASE_URL
        value: "postgres://elearning_1ycv_user:Z2aBvVwWQXCFi3uZ1fJgPlKBDSzqj62U@dpg-cgrauugrddl6f7fcq08g-a.oregon-postgres.render.com/elearning_1ycv"
"
