# .render.yaml

services:
  - name: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    env:
      - name: DATABASE_URL
        value: "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
